Allow bootstrap to download some automake dependencies if they are not installed

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -81,7 +81,7 @@ env_get_m4_req()
 {
 	# Unfortunately this is a hard-coded list. It must be kept up-to-date
 	# when automake dependencies are added or dropped.
-	m4_req='ax_prog_doxygen.m4'
+	m4_req='ax_prog_doxygen.m4:http://mirrors.ocf.berkeley.edu/gnu/autoconf-archive/autoconf-archive-2015.09.25.tar.xz'
 }
 
 ## Set the search path for automake macro files.
@@ -152,12 +152,97 @@ env_set_m4_path()
 	fi
 }
 
+## Download an automake macro file from the given URL.
+env_download_m4_file()
+{
+	if [ "x$1" = 'x' ]; then
+		echo "env_download_m4_file: BUG! No m4 macro file to find" 1>&2
+		exit 1
+	fi
+	__file="$1"
+
+	if [ "x$2" = 'x' ]; then
+		echo "env_download_m4_file: BUG! No URL for $__file" 1>&2
+		exit 1
+	fi
+	__url="$2"
+
+	__downloaded_file_path="$(find $PWD/aclocal -name $__file 2>/dev/null | head -n1)"
+	if [ "x$__downloaded_file_path" = 'x' ]; then
+		__downloaded_file_name="$(basename $__url)"
+		if [ "x$__downloaded_file_name" = 'x' ]; then
+			echo "Error: Failed to extract the base file name from $__url" 1>&2
+			exit 1
+		fi
+
+		case $__downloaded_file_name in
+			*.tar.xz)
+				__archive_extract_command='tar xJf'
+				;;
+
+			*.tar.bz2)
+				__archive_extract_command='tar xjf'
+				;;
+
+			*.tar.gz|*.tgz)
+				__archive_extract_command='tar xzf'
+				;;
+
+			*)
+				echo "Error: Unknown archive type $__url" 1>&2
+				exit 1
+				;;
+		esac
+
+		if [ ! -d aclocal ] && ! mkdir aclocal; then
+			echo "Error: Failed to make the aclocal directory" 1>&2
+			exit 1
+		fi
+
+		cd aclocal
+		if ! wget $__url; then
+			echo "Error: Failed to download $__file from $__url" 1>&2
+			rm -rf $__downloaded_file_name
+			exit 1
+		elif ! $__archive_extract_command $__downloaded_file_name; then
+			echo "Error: Failed to extract $__file from $__downloaded_file_name" 1>&2
+			rm -rf ${__downloaded_file_name}*
+			exit 1
+		fi
+		cd ..
+
+		__downloaded_file_path="$(find $PWD/aclocal -name $__file 2>/dev/null | head -n1)"
+		if [ "x$__downloaded_file_path" = 'x' ]; then
+			echo "Error: Could not find $__file in the archive downloaded from $__url" 1>&2
+			rm -rf ${__downloaded_file_name}*
+			exit 1
+		fi
+	else
+		unset __downloaded_file_name
+		unset __archive_extract_command
+	fi
+
+	__downloaded_file_base_path="$(dirname $__downloaded_file_path)"
+	if [ "x$__downloaded_file_base_path" = 'x' ]; then
+		echo "Error: Failed to extract the base search path of $__file from $__downloaded_file_path" 1>&2
+		if [ "x$__downloaded_file_name" != 'x' ]; then
+			rm -rf ${__downloaded_file_name}*
+		fi
+		exit 1
+	fi
+
+	if [ "x$ACLOCAL_PATH" = 'x' ]; then
+		export ACLOCAL_PATH="$__downloaded_file_base_path"
+	else
+		export ACLOCAL_PATH="${ACLOCAL_PATH}:${__downloaded_file_base_path}"
+	fi
+
+	# Update $m4_search_path now that $ACLOCAL_PATH has been updated with the
+	# new search path.
+	env_set_m4_path
+}
+
 ## Try to find the given automake macro file in the search path.
-#
-# Note: This function requires $m4_search_path to contain a colon-delimited
-# list of the paths that you want to search for automake macro files. Call
-# env_set_m4_path() first to properly setup those paths.
-#
 env_find_m4_file()
 {
 	if [ "x$1" = 'x' ]; then
@@ -165,6 +250,12 @@ env_find_m4_file()
 		exit 1
 	fi
 	__file="$1"
+
+	if [ "x$2" = 'x' ]; then
+		unset __url
+	else
+		__url="$2"
+	fi
 
 	if [ "x$m4_search_path" = 'x' ]; then
 		echo "env_find_m4_file: BUG! No search path for m4 macro files" 1>&2
@@ -180,8 +271,13 @@ env_find_m4_file()
 		fi
 	done
 	if [ $__file_found -eq 0 ]; then
-		echo "not found" 1>&2
-		exit 1
+		if [ $download -eq 0 ] || [ "x$__url" = 'x' ]; then
+			echo "not found" 1>&2
+			exit 1
+		fi
+
+		echo "downloading" 1>&2
+		env_download_m4_file $__file $__url
 	else
 		echo "found" 1>&2
 	fi
@@ -194,7 +290,10 @@ env_find_m4_req()
 	env_get_m4_req
 
 	for __req_file in $m4_req; do
-		env_find_m4_file $__req_file
+		__req_file_name=$(echo $__req_file | cut -d: -f1)
+		__req_file_url=$(echo $__req_file | cut -d: -f2-)
+
+		env_find_m4_file $__req_file_name $__req_file_url
 	done
 }
 
@@ -239,6 +338,7 @@ env_find_am()
 ## Cleanup the artifacts generated by bootstrap and configure.
 action_clean()
 {
+	rm -vrf aclocal
 	rm -vf aclocal.m4
 	rm -vrf autom4te.cache/
 	rm -vrf build-aux/
@@ -277,11 +377,14 @@ action_generate()
 ## Print our help information.
 action_help()
 {
-	echo "Usage: $0 [ACTION]
+	echo "Usage: $0 [OPTIONS] [ACTION]
 
 Actions:
   gen|generate             generate the build scripts for SimplePost
   clean                    cleanup the artifacts generated by bootstrap and configure
+
+Options:
+  -n, --no-download        do not attempt to automatically download missing automake dependencies
 "
 }
 
@@ -290,7 +393,41 @@ Actions:
 ###############################################################################
 
 action='generate'
+download=1
 
+# Process command line options
+while [ $# -gt 0 ]; do
+	case "$1" in
+		-n|--no-download)
+			download=0
+			;;
+
+		--help)
+			# This is a special case. Break now to allow the help option to be
+			# handled as an action.
+			break
+			;;
+
+		-*)
+			echo "Invalid Option: $1" 1>&2
+			exit 1
+			;;
+
+		*)
+			if [ $# -gt 1 ]; then
+				echo "Invalid Option: $1" 1>&2
+				exit 1
+			else
+				# Break now to avoid another shift. Since this is the final
+				# command line argument attempt to handle it as an action.
+				break
+			fi
+			;;
+	esac
+	shift
+done
+
+# Process command line actions
 while [ $# -gt 0 ]; do
 	case "$1" in
 		gen|generate)
