Download a new m4 macro file by default if the version doesn't match
Prior to this commit, the bootstrap script would automatically download a
required m4 macro file from the Internet if it could not be found on the
system (and it wasn't explicitly disallowed with the "-n" switch). This
allowed distros that don't ship autoconf-archive but *do* have new enough
versions of autoconf and automake to bootstrap the configure script. Then I
introduced version checking for certain macro files, and if the file was
found but the version was too old, bootstrap would fail. This patch enables
the same functionality if the version does not match: the bootstrap script
will try to automatically download a new version of the m4 macro file if it
can.

Since the version of autoconf-archive shipped with Debian Jessie and Ubuntu
16.04 is too old for us to use, this patch allows us to bootstrap on those
distros once again.

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -316,10 +316,16 @@ env_check_m4_ver()
 	fi
 	__file="$1"
 
-	if [ "x$2" = 'x' ]; then
+	if [ "x$2" = 'x' ] || ! echo "$2" | grep -Eqs '^[0-9]+$'; then
 		__ver=0
 	else
 		__ver="$2"
+	fi
+
+	if [ "x$3" = 'x' ]; then
+		unset __url
+	else
+		__url="$3"
 	fi
 
 	if ! echo "$__ver" | grep -Eqs '^([0-9]+\.)*[0-9]+$'; then
@@ -336,8 +342,17 @@ env_check_m4_ver()
 		fi
 
 		if [ "$__real_ver" != "$__ver" ] && verlte $__real_ver $__ver; then
-			echo "$__real_ver (v$__ver or later required)" 1>&2
-			exit 1
+			if [ $download -eq 0 ] || [ "x$__url" = 'x' ]; then
+				echo "$__real_ver (v$__ver or later required)" 1>&2
+				exit 1
+			fi
+
+			echo "$__real_ver (downloading v$__ver or later)" 1>&2
+			env_download_m4_file $(basename "$__file") $__url
+			if [ "x$m4_file_path" = 'x' ]; then
+				echo "env_find_m4_file: BUG! env_download_m4_file did not set m4 macro file path" 1>&2
+				exit 1
+			fi
 		else
 			echo "$__real_ver" 1>&2
 		fi
@@ -356,7 +371,7 @@ env_find_m4_req()
 		__req_file_url=$(echo $__req_file | cut -d: -f3-)
 
 		env_find_m4_file $__req_file_name $__req_file_url
-		env_check_m4_ver "$m4_file_path" $__req_file_ver
+		env_check_m4_ver "$m4_file_path" $__req_file_ver $__req_file_url
 	done
 }
 
